(define (save-data data addr)
  (let ((port (open-output-file addr #:exists 'update)))
    (write data port)
    (close-output-port port)))

(define (load-data addr)
  (let ((port (open-input-file addr)))
    (let ((r (read port)))
      (close-input-port port)
      r)))

(define (lines-count addr)
  (let ((port (open-input-file addr)))
    (let loop ((lines 0) (chars 0))
      (if (eof-object? (peek-char port))
          (begin (close-input-port port)
                 (if (> chars 0)
                     (+ lines 1)
                     lines))
          (if (equal? (read-char port) #\newline)
              (if (> chars 0)
                  (loop (+ lines 1) 0)
                  (loop lines 0))
              (loop lines (+ chars 1)))))))
