(define (read-words)
  (let loop ((words '()) (word ""))
    (if (eof-object? (peek-char))
        (reverse (if (> (string-length word) 0)
                     (cons word words)
                     words))
        (let ((char (read-char)))
          (if (or (equal? char #\space)
                  (equal? char #\newline)
                  (equal? char #\tab))
              (if (> (string-length word) 0)
                  (loop (cons word words) "")
                  (loop words ""))
              (loop words (string-append word
                                         (string char))))))))
